// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AirportsColumns holds the columns for the "airports" table.
	AirportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ident", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "latitude_deg", Type: field.TypeFloat64},
		{Name: "longitude_deg", Type: field.TypeFloat64},
		{Name: "elevation_ft", Type: field.TypeInt},
		{Name: "continent", Type: field.TypeString},
		{Name: "iso_country", Type: field.TypeString},
		{Name: "iso_region", Type: field.TypeString},
		{Name: "municipality", Type: field.TypeString},
		{Name: "scheduled_service", Type: field.TypeString},
		{Name: "gps_code", Type: field.TypeString},
		{Name: "local_code", Type: field.TypeString},
	}
	// AirportsTable holds the schema information for the "airports" table.
	AirportsTable = &schema.Table{
		Name:       "airports",
		Columns:    AirportsColumns,
		PrimaryKey: []*schema.Column{AirportsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AirportsTable,
		UsersTable,
	}
)

func init() {
}
