// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rena-0/poc-ent/ent/airport"
)

// AirportCreate is the builder for creating a Airport entity.
type AirportCreate struct {
	config
	mutation *AirportMutation
	hooks    []Hook
}

// SetIdent sets the "ident" field.
func (ac *AirportCreate) SetIdent(s string) *AirportCreate {
	ac.mutation.SetIdent(s)
	return ac
}

// SetType sets the "type" field.
func (ac *AirportCreate) SetType(s string) *AirportCreate {
	ac.mutation.SetType(s)
	return ac
}

// SetName sets the "name" field.
func (ac *AirportCreate) SetName(s string) *AirportCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetLatitudeDeg sets the "latitude_deg" field.
func (ac *AirportCreate) SetLatitudeDeg(f float64) *AirportCreate {
	ac.mutation.SetLatitudeDeg(f)
	return ac
}

// SetLongitudeDeg sets the "longitude_deg" field.
func (ac *AirportCreate) SetLongitudeDeg(f float64) *AirportCreate {
	ac.mutation.SetLongitudeDeg(f)
	return ac
}

// SetElevationFt sets the "elevation_ft" field.
func (ac *AirportCreate) SetElevationFt(i int) *AirportCreate {
	ac.mutation.SetElevationFt(i)
	return ac
}

// SetContinent sets the "continent" field.
func (ac *AirportCreate) SetContinent(s string) *AirportCreate {
	ac.mutation.SetContinent(s)
	return ac
}

// SetIsoCountry sets the "iso_country" field.
func (ac *AirportCreate) SetIsoCountry(s string) *AirportCreate {
	ac.mutation.SetIsoCountry(s)
	return ac
}

// SetIsoRegion sets the "iso_region" field.
func (ac *AirportCreate) SetIsoRegion(s string) *AirportCreate {
	ac.mutation.SetIsoRegion(s)
	return ac
}

// SetMunicipality sets the "municipality" field.
func (ac *AirportCreate) SetMunicipality(s string) *AirportCreate {
	ac.mutation.SetMunicipality(s)
	return ac
}

// SetScheduledService sets the "scheduled_service" field.
func (ac *AirportCreate) SetScheduledService(s string) *AirportCreate {
	ac.mutation.SetScheduledService(s)
	return ac
}

// SetGpsCode sets the "gps_code" field.
func (ac *AirportCreate) SetGpsCode(s string) *AirportCreate {
	ac.mutation.SetGpsCode(s)
	return ac
}

// SetLocalCode sets the "local_code" field.
func (ac *AirportCreate) SetLocalCode(s string) *AirportCreate {
	ac.mutation.SetLocalCode(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AirportCreate) SetID(i int) *AirportCreate {
	ac.mutation.SetID(i)
	return ac
}

// Mutation returns the AirportMutation object of the builder.
func (ac *AirportCreate) Mutation() *AirportMutation {
	return ac.mutation
}

// Save creates the Airport in the database.
func (ac *AirportCreate) Save(ctx context.Context) (*Airport, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AirportCreate) SaveX(ctx context.Context) *Airport {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AirportCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AirportCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AirportCreate) check() error {
	if _, ok := ac.mutation.Ident(); !ok {
		return &ValidationError{Name: "ident", err: errors.New(`ent: missing required field "Airport.ident"`)}
	}
	if v, ok := ac.mutation.Ident(); ok {
		if err := airport.IdentValidator(v); err != nil {
			return &ValidationError{Name: "ident", err: fmt.Errorf(`ent: validator failed for field "Airport.ident": %w`, err)}
		}
	}
	if _, ok := ac.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Airport.type"`)}
	}
	if v, ok := ac.mutation.GetType(); ok {
		if err := airport.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Airport.type": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Airport.name"`)}
	}
	if v, ok := ac.mutation.Name(); ok {
		if err := airport.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Airport.name": %w`, err)}
		}
	}
	if _, ok := ac.mutation.LatitudeDeg(); !ok {
		return &ValidationError{Name: "latitude_deg", err: errors.New(`ent: missing required field "Airport.latitude_deg"`)}
	}
	if _, ok := ac.mutation.LongitudeDeg(); !ok {
		return &ValidationError{Name: "longitude_deg", err: errors.New(`ent: missing required field "Airport.longitude_deg"`)}
	}
	if _, ok := ac.mutation.ElevationFt(); !ok {
		return &ValidationError{Name: "elevation_ft", err: errors.New(`ent: missing required field "Airport.elevation_ft"`)}
	}
	if _, ok := ac.mutation.Continent(); !ok {
		return &ValidationError{Name: "continent", err: errors.New(`ent: missing required field "Airport.continent"`)}
	}
	if v, ok := ac.mutation.Continent(); ok {
		if err := airport.ContinentValidator(v); err != nil {
			return &ValidationError{Name: "continent", err: fmt.Errorf(`ent: validator failed for field "Airport.continent": %w`, err)}
		}
	}
	if _, ok := ac.mutation.IsoCountry(); !ok {
		return &ValidationError{Name: "iso_country", err: errors.New(`ent: missing required field "Airport.iso_country"`)}
	}
	if v, ok := ac.mutation.IsoCountry(); ok {
		if err := airport.IsoCountryValidator(v); err != nil {
			return &ValidationError{Name: "iso_country", err: fmt.Errorf(`ent: validator failed for field "Airport.iso_country": %w`, err)}
		}
	}
	if _, ok := ac.mutation.IsoRegion(); !ok {
		return &ValidationError{Name: "iso_region", err: errors.New(`ent: missing required field "Airport.iso_region"`)}
	}
	if v, ok := ac.mutation.IsoRegion(); ok {
		if err := airport.IsoRegionValidator(v); err != nil {
			return &ValidationError{Name: "iso_region", err: fmt.Errorf(`ent: validator failed for field "Airport.iso_region": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Municipality(); !ok {
		return &ValidationError{Name: "municipality", err: errors.New(`ent: missing required field "Airport.municipality"`)}
	}
	if v, ok := ac.mutation.Municipality(); ok {
		if err := airport.MunicipalityValidator(v); err != nil {
			return &ValidationError{Name: "municipality", err: fmt.Errorf(`ent: validator failed for field "Airport.municipality": %w`, err)}
		}
	}
	if _, ok := ac.mutation.ScheduledService(); !ok {
		return &ValidationError{Name: "scheduled_service", err: errors.New(`ent: missing required field "Airport.scheduled_service"`)}
	}
	if v, ok := ac.mutation.ScheduledService(); ok {
		if err := airport.ScheduledServiceValidator(v); err != nil {
			return &ValidationError{Name: "scheduled_service", err: fmt.Errorf(`ent: validator failed for field "Airport.scheduled_service": %w`, err)}
		}
	}
	if _, ok := ac.mutation.GpsCode(); !ok {
		return &ValidationError{Name: "gps_code", err: errors.New(`ent: missing required field "Airport.gps_code"`)}
	}
	if v, ok := ac.mutation.GpsCode(); ok {
		if err := airport.GpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "gps_code", err: fmt.Errorf(`ent: validator failed for field "Airport.gps_code": %w`, err)}
		}
	}
	if _, ok := ac.mutation.LocalCode(); !ok {
		return &ValidationError{Name: "local_code", err: errors.New(`ent: missing required field "Airport.local_code"`)}
	}
	if v, ok := ac.mutation.LocalCode(); ok {
		if err := airport.LocalCodeValidator(v); err != nil {
			return &ValidationError{Name: "local_code", err: fmt.Errorf(`ent: validator failed for field "Airport.local_code": %w`, err)}
		}
	}
	return nil
}

func (ac *AirportCreate) sqlSave(ctx context.Context) (*Airport, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AirportCreate) createSpec() (*Airport, *sqlgraph.CreateSpec) {
	var (
		_node = &Airport{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(airport.Table, sqlgraph.NewFieldSpec(airport.FieldID, field.TypeInt))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Ident(); ok {
		_spec.SetField(airport.FieldIdent, field.TypeString, value)
		_node.Ident = value
	}
	if value, ok := ac.mutation.GetType(); ok {
		_spec.SetField(airport.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(airport.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.LatitudeDeg(); ok {
		_spec.SetField(airport.FieldLatitudeDeg, field.TypeFloat64, value)
		_node.LatitudeDeg = value
	}
	if value, ok := ac.mutation.LongitudeDeg(); ok {
		_spec.SetField(airport.FieldLongitudeDeg, field.TypeFloat64, value)
		_node.LongitudeDeg = value
	}
	if value, ok := ac.mutation.ElevationFt(); ok {
		_spec.SetField(airport.FieldElevationFt, field.TypeInt, value)
		_node.ElevationFt = value
	}
	if value, ok := ac.mutation.Continent(); ok {
		_spec.SetField(airport.FieldContinent, field.TypeString, value)
		_node.Continent = value
	}
	if value, ok := ac.mutation.IsoCountry(); ok {
		_spec.SetField(airport.FieldIsoCountry, field.TypeString, value)
		_node.IsoCountry = value
	}
	if value, ok := ac.mutation.IsoRegion(); ok {
		_spec.SetField(airport.FieldIsoRegion, field.TypeString, value)
		_node.IsoRegion = value
	}
	if value, ok := ac.mutation.Municipality(); ok {
		_spec.SetField(airport.FieldMunicipality, field.TypeString, value)
		_node.Municipality = value
	}
	if value, ok := ac.mutation.ScheduledService(); ok {
		_spec.SetField(airport.FieldScheduledService, field.TypeString, value)
		_node.ScheduledService = value
	}
	if value, ok := ac.mutation.GpsCode(); ok {
		_spec.SetField(airport.FieldGpsCode, field.TypeString, value)
		_node.GpsCode = value
	}
	if value, ok := ac.mutation.LocalCode(); ok {
		_spec.SetField(airport.FieldLocalCode, field.TypeString, value)
		_node.LocalCode = value
	}
	return _node, _spec
}

// AirportCreateBulk is the builder for creating many Airport entities in bulk.
type AirportCreateBulk struct {
	config
	err      error
	builders []*AirportCreate
}

// Save creates the Airport entities in the database.
func (acb *AirportCreateBulk) Save(ctx context.Context) ([]*Airport, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Airport, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AirportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AirportCreateBulk) SaveX(ctx context.Context) []*Airport {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AirportCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AirportCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
