// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Airport is the predicate function for airport builders.
type Airport func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
